# Service wso2am-km-service
apiVersion: v1
kind: Service
metadata:
  name: kcb-wso2apim-km-service
  namespace: kcb-wso2apim  
spec:  
  type: ClusterIP
  ports:
    - name: kcb-servlet-https1
      port: 8243
      protocol: TCP
      targetPort: 8243
    - name: kcb-servlet-https2
      port: 9763
      protocol: TCP
      targetPort: 9763
    - name: kcb-servlet-https3
      port: 9443
      protocol: TCP
      targetPort: 9443   
  selector:
    deploymentName: kcb-wso2apim-km-deployment