# Service wso2am-km-service
apiVersion: v1
kind: Service
metadata:
  name: wso2am-km-service
spec:
  type: ClusterIP
  ports:
    - name: servlet-https
      port: 9443
      protocol: TCP
      targetPort: 9443
  selector:
    deploymentName: wso2am-km