apiVersion: v1
kind: ConfigMap
metadata:
  name: kcb-wso2apim-devportal-conf
  namespace : kcb-wso2apim    
data:
  deployment.toml: |-
    [server]
    hostname = "devportal.am.wso2.com"
    node_ip = "$env{NODE_IP}"
    server_role="api-devportal"
    offset=2

    [user_store]
    type = "database_unique_id"

    [super_admin]
    username = "admin"
    password = "admin"
    create_admin_account = true

    [database.apim_db]
    type = "mysql"
    url = "jdbc:mysql://kcb-wso2am-mysql-db-service:3306/WSO2AM_DB?useSSL=false&amp;autoReconnect=true&amp;requireSSL=false&amp;verifyServerCertificate=false"
    username = "wso2carbon"
    password = "wso2carbon"
    driver = "com.mysql.cj.jdbc.Driver"

    [database.shared_db]
    type = "mysql"
    url = "jdbc:mysql://kcb-wso2am-mysql-db-service:3306/WSO2AM_SHARED_DB?useSSL=false&amp;autoReconnect=true&amp;requireSSL=false&amp;verifyServerCertificate=false"
    username = "wso2carbon"
    password = "wso2carbon"
    driver = "com.mysql.cj.jdbc.Driver"
    pool_options.maxActive=300

    [keystore.tls]
    file_name =  "wso2carbon.jks"
    type =  "JKS"
    password =  "wso2carbon"
    alias =  "wso2carbon"
    key_password =  "wso2carbon"

    [truststore]
    file_name = "client-truststore.jks"
    type = "JKS"
    password = "wso2carbon"

    # key manager implementation
    [apim.key_manager]
    service_url = "https://kcb-wso2apim-km-service:9443/services/"
    username= "$ref{super_admin.username}"
    password= "$ref{super_admin.password}"
    [[apim.gateway.environment]]
    name= "Production and Sandbox"
    type= "hybrid"
    display_in_api_console= true
    description= "This is a hybrid gateway that handles both production and sandbox token traffic."
    service_url= "https://kcb-wso2apim-gateway-service:9447/services/"
    username= "${admin.username}"
    password= "${admin.password}"
    ws_endpoint = "ws://kcb-wso2apim-gateway-service:9103"
    wss_endpoint = "wss://kcb-wso2apim-gateway-service:8103"
    http_endpoint = "http://kcb-wso2apim-gateway-service:8284/"
    https_endpoint = "https://kcb-wso2apim-gateway-service:8247/" 
    show_as_token_endpoint_url = true    

    [apim.cache.tags]
    expiry_time = 120000        

    [apim.devportal]
    enable_application_sharing = true
    application_sharing_type = "default" #changed to type, saml, default
    #application_sharing_impl = "org.wso2.carbon.apimgt.impl.DefaultGroupIDExtractorImpl"
    display_multiple_versions = false
    display_deprecated_apis = false
    enable_comments = true
    enable_ratings = true
    enable_forum = true

    [apim.oauth_config]
    revoke_endpoint = "https://kcb-wso2apim-km-service:9443/oauth2/revoke"

    [[event_handler]]
    name="userPostSelfRegistration"
    subscriptions=["POST_ADD_USER"]
   
    # Traffic Manager configurations
    [apim.throttling]
    username= "$ref{super_admin.username}"
    password= "$ref{super_admin.password}"
    throttle_decision_endpoints = ["tcp://kcb-wso2apim-tm-service:5675"]

    [[apim.throttling.url_group]]
    traffic_manager_urls = ["tcp://kcb-wso2apim-tm-service:9614"]
    traffic_manager_auth_urls = ["ssl://kcb-wso2apim-tm-service:9714"]
