# DeploymentConfig wso2am-gateway-deployment
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: wso2apim-gateway-deployment
  namespace: wso2apim
spec:
  replicas: 1
  selector:
      deploymentName: wso2apim-gateway      
  strategy:
      type: Rolling
  template:
      metadata:
        labels:
          deploymentName: wso2apim-gateway
      spec:
        containers:
          - env:
              - name: PROFILE_NAME
                value: gateway-worker
              - name: NODE_IP
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: status.podIP
            image: 'wso2/wso2am:3.1.0'
            imagePullPolicy: IfNotPresent
            lifecycle:
              preStop:
                exec:
                  command:
                    - sh
                    - '-c'
                    - '${WSO2_SERVER_HOME}/bin/wso2server.sh stop'
            name: wso2apim-gw
            livenessProbe:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - nc -z localhost 9447
              failureThreshold: 3
              initialDelaySeconds: 500
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            readinessProbe:
              exec:
                command:
                - /bin/sh
                - -c
                - nc -z localhost 9447
              failureThreshold: 3
              initialDelaySeconds: 500
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            ports:
              - containerPort: 8284
                protocol: TCP
              - containerPort: 8247
                protocol: TCP
              - containerPort: 9767
                protocol: TCP
              - containerPort: 9447
                protocol: TCP
            resources:
              limits:
                cpu: 400m
                memory: 2Gi
              requests:
                cpu: 400m
                memory: 2Gi
            volumeMounts:
              # - mountPath: /home/wso2carbon/wso2-artifact-volume/repository/deployment/server/synapse-configs
              #   name: wso2apim-volume-claim-synapse-configs
              - mountPath: /home/wso2carbon/wso2-config-volume/repository/conf/deployment.toml
                name: wso2apim-gateway-conf
                subPath: deployment.toml             
        imagePullSecrets:
        - name: ""        
        restartPolicy: Always
        securityContext:
          runAsUser: 802
        serviceAccount: wso2am-svc-account
        serviceAccountName: wso2am-svc-account
        volumes:
        # - name: wso2apim-volume-claim-synapse-configs
        #   persistentVolumeClaim:
        #     claimName: wso2apim-volume-claim-synapse-configs
        - configMap:            
            name: wso2apim-gateway-conf
          name: wso2apim-gateway-conf        
  triggers:
      - type: ConfigChange    