apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: wso2apim-devportal-deployment
  namespace: wso2apim  
spec:
  replicas: 1
  strategy:
    type: Rolling
  selector:
     deployment: wso2apim-devportal          
  template:
    metadata:     
      labels:
        deployment: wso2apim-devportal
    spec:
      initContainers:        
        - name: init-apim-db
          image: busybox:1.32
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'echo -e "Checking for the availability of DBMS service"; while ! nc -z "wso2am-mysql-db-service" 3306; do sleep 1; printf "-"; done; echo -e "  >> DBMS service is available";']
        - name: init-mysql-connector-download
          image: busybox:1.32
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - "-c"
            - |
              set -e
              connector_version=8.0.17
              wget https://repo1.maven.org/maven2/mysql/mysql-connector-java/${connector_version}/mysql-connector-java-${connector_version}.jar -P /mysql-connector-jar/
          volumeMounts:
            - name: mysql-connector-jar
              mountPath: /mysql-connector-jar
        #- name: init-apim-analytics
          #image: 'busybox:1.32'
          #imagePullPolicy: IfNotPresent
          #command: ['sh', '-c', 'echo -e "Checking for the availability of WSO2 API Manager Analytics Worker deployment"; while ! nc -z wso2apim-analytics-worker-service 7712; do sleep 1; printf "-"; done; echo -e "  >> WSO2 API Manager Analytics Worker has started";']
        #- name: init-km
          #image: 'busybox:1.32'
          #imagePullPolicy: IfNotPresent
          #command: ['sh', '-c', 'echo -e "Checking for the availability of Key Manager deployment"; while ! nc -z wso2apim-km-service 9443; do sleep 1; printf "-"; done; echo -e "  >> Key Manager has started";']
      containers:
        - name: wso2apim-devportal          
          image: 'wso2/wso2am:3.1.0'          
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nc -z localhost 9443
            initialDelaySeconds: 500
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nc -z localhost 9443
            initialDelaySeconds: 500
            periodSeconds: 10
          lifecycle:
            preStop:
              exec:
                command: ['sh', '-c', '${WSO2_SERVER_HOME}/bin/wso2server.sh stop']
          resources:
            requests:
              memory: 1Gi
              cpu: 100m
            limits:
              memory: 1Gi
              cpu: 100m
          ports:
            - containerPort: 9763
              protocol: "TCP"
            - containerPort: 9443
              protocol: "TCP"
          env:
            - name: PROFILE_NAME
              value: api-devportal
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: JVM_MEM_OPTS
              value: "-Xms512m -Xmx512m"
          securityContext:
            runAsUser: 802
          volumeMounts:
          - name: wso2apim-devportal-conf
            mountPath: /home/wso2carbon/wso2-config-volume/repository/conf         
          - name: wso2apim-devportal-local-carbon-database-storage
            mountPath: /home/wso2carbon/solr/database
          - name: wso2apim-devportal-indexed-data-volume
            mountPath: /home/wso2carbon/solr/indexed-data
          - name: wso2apim-devportal-conf-entrypoint
            mountPath: /home/wso2carbon/docker-entrypoint.sh
            subPath: docker-entrypoint.sh
          - name: mysql-connector-jar
            mountPath: /home/wso2carbon/wso2-artifact-volume/repository/components/dropins                   
      serviceAccountName: wso2am-svc-account
      imagePullSecrets:
        - name: ""
      volumes:
        - name: wso2apim-devportal-conf
          configMap:
            name: wso2apim-devportal-conf        
        - name: wso2apim-devportal-conf-entrypoint
          configMap:
            name: wso2apim-devportal-conf-entrypoint
            defaultMode: 0407
        - name: wso2apim-devportal-local-carbon-database-storage
          persistentVolumeClaim:
            claimName: wso2apim-devportal-local-carbon-database-volume-claim
        - name: wso2apim-devportal-indexed-data-volume
          persistentVolumeClaim:
            claimName: wso2apim-devportal-solr-indexed-data-volume-claim 
        - name: mysql-connector-jar
          emptyDir: {}  
  triggers:
      - type: ConfigChange    