apiVersion: v1
kind: ConfigMap
metadata:
  name: wso2apim-publisher-conf
  namespace : wso2apim  
data:
  deployment.toml: |-
    [server]
    hostname = "publisher.am.wso2.com"
    node_ip = "$env{NODE_IP}"
    server_role = "api-publisher"
    base_path = "https://publisher.am.wso2.com"
    offset=1

    [user_store]
    type = "database_unique_id"

    [super_admin]
    username = "admin"
    password = "admin"
    create_admin_account = true

    [database.apim_db]
    type = "mysql"
    url = "jdbc:mysql://wso2am-mysql-db-service:3306/WSO2AM_DB?useSSL=false&amp;autoReconnect=true&amp;requireSSL=false&amp;verifyServerCertificate=false"
    username = "wso2carbon"
    password = "wso2carbon"
    driver = "com.mysql.cj.jdbc.Driver"
    pool_options.maxActive=300

    [database.shared_db]
    type = "mysql"
    url = "jdbc:mysql://wso2am-mysql-db-service:3306/WSO2AM_SHARED_DB?useSSL=false&amp;autoReconnect=true&amp;requireSSL=false&amp;verifyServerCertificate=false"
    username = "wso2carbon"
    password = "wso2carbon"
    driver = "com.mysql.cj.jdbc.Driver"
    pool_options.maxActive=300

    [keystore.tls]
    file_name =  "wso2carbon.jks"
    type =  "JKS"
    password =  "wso2carbon"
    alias =  "wso2carbon"
    key_password =  "wso2carbon"

    [truststore]
    file_name = "client-truststore.jks"
    type = "JKS"
    password = "wso2carbon"

    [[apim.gateway.environment]]
    name= "Production and Sandbox"
    type= "hybrid"
    display_in_api_console= true
    description= "This is a hybrid gateway that handles both production and sandbox token traffic."
    service_url= "https://wso2apim-gateway-service:9447/services/"
    username= "${admin.username}"
    password= "${admin.password}"
    ws_endpoint = "ws://lowso2apim-gateway-service:9103"
    wss_endpoint = "wss://wso2apim-gateway-service:8103"
    http_endpoint = "http://wso2apim-gateway-service:8284/"
    https_endpoint = "https://wso2apim-gateway-service:8247/"        

    # key manager implementation
    [apim.key_manager]
    service_url = "https://wso2apim-km-service:9443/services/"
    username= "$ref{super_admin.username}"
    password= "$ref{super_admin.password}"  

    # Traffic Manager configurations
    [apim.throttling]
    username= "$ref{super_admin.username}"
    password= "$ref{super_admin.password}"
    service_url = "https://wso2apim-tm-service:9446/services/"
    throttle_decision_endpoints = ["tcp://wso2apim-tm-service:5675"]

    [[apim.throttling.url_group]]
    traffic_manager_urls = ["tcp://wso2apim-tm-service:9614"]
    traffic_manager_auth_urls = ["ssl://wso2apim-tm-service:9714"]

    [apim.devportal]
    url = "https://wso2apim-devportal-service:9445/devportal"
