# DeploymentConfig wso2am-am-analytics-worker-deployment
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: wso2am-am-analytics-worker-deployment
spec:
  replicas: 1
  selector:
    deploymentName: wso2am-analytics-worker
  strategy:
      type: Rolling
  template:
      metadata:
        labels:
          app-analytic: wso2am-analytics-worker
          deploymentName: wso2am-analytics-worker
      spec:
        containers:
          - image: 'wso2/wso2am-analytics-worker:3.1.0'
            lifecycle:
              preStop:
                exec:
                  command:
                    - sh
                    - '-c'
                    - '${WSO2_SERVER_HOME}/bin/worker.sh stop'
            livenessProbe:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - nc -z localhost 9444
              failureThreshold: 3
              initialDelaySeconds: 20
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            name: wso2am-analytics-worker
            ports:
              - containerPort: 9764
                protocol: TCP
              - containerPort: 9444
                protocol: TCP
              - containerPort: 7612
                protocol: TCP
              - containerPort: 7712
                protocol: TCP
              - containerPort: 9091
                protocol: TCP
              - containerPort: 7071
                protocol: TCP
              - containerPort: 7444
                protocol: TCP
            readinessProbe:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - nc -z localhost 9444
              failureThreshold: 3
              initialDelaySeconds: 20
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            resources:
              limits:
                cpu: 2000m
                memory: 4Gi
              requests:
                cpu: 2000m
                memory: 4Gi
            volumeMounts:
              - mountPath: /home/wso2carbon/wso2-config-volume/conf/worker/deployment.yaml
                name: wso2am-analytics-worker-conf
                subPath: deployment.yaml
        imagePullSecrets:
        - name: ${IMAGE_PULL_SECRET}
        initContainers:
          - command:
              - sh
              - '-c'
              - >-
                echo -e "Checking for the availability of MySQL Server
                deployment"; while ! nc -z "wso2am-mysql-db-service" 3306; do
                sleep 1; printf "-"; done; echo -e "  >> MySQL Server has
                started";
            image: 'busybox:1.31'
            imagePullPolicy: IfNotPresent
            name: init-apim-analytics-db
        restartPolicy: Always
        securityContext:
          runAsUser: 802
        serviceAccount: wso2am-svc-account
        serviceAccountName: wso2am-svc-account
        terminationGracePeriodSeconds: 30
        volumes:
          - configMap:
              defaultMode: 420
              name: wso2am-analytics-worker-conf
            name: wso2am-analytics-worker-conf
  triggers:
      - type: ConfigChange