# DeploymentConfig wso2am-am-analytics-worker-deployment
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: wso2apim-analytics-worker-deployment
  namespace: wso2apim  
spec:
  replicas: 1
  selector:
    deployment: wso2apim-analytics-worker
  strategy:
      type: Rolling
  template:
      metadata:
        labels:
          app-analytic: wso2apim-analytics-worker
          deployment: wso2apim-analytics-worker
      spec:
        containers:
          - image: 'wso2/wso2am-analytics-worker:3.1.0'
            env:
             - name: PROFILE_NAME
               value: api-devportal
             - name: NODE_IP
               valueFrom:
                 fieldRef:
                   fieldPath: status.podIP
             - name: JVM_MEM_OPTS
               value: "-Xms512m -Xmx512m"           
            livenessProbe:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - nc -z localhost 9444
              failureThreshold: 3
              initialDelaySeconds: 120
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            name: wso2apim-analytics-worker
            ports:
              - containerPort: 9764
                protocol: TCP
              - containerPort: 9444
                protocol: TCP
              - containerPort: 7612
                protocol: TCP
              - containerPort: 7712
                protocol: TCP
              - containerPort: 9091
                protocol: TCP
              - containerPort: 7071
                protocol: TCP
              - containerPort: 7444
                protocol: TCP
            readinessProbe:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - nc -z localhost 9444
              failureThreshold: 3
              initialDelaySeconds: 120
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            resources:
              limits:
                cpu: 500m
                memory: 2Gi
              requests:
                cpu: 500m
                memory: 2Gi
            volumeMounts:
              - mountPath: /home/wso2carbon/wso2-config-volume/conf/worker/deployment.yaml
                name: wso2apim-analytics-worker-conf
                subPath: deployment.yaml
              - name: wso2apim-analytics-worker-bin
                mountPath: /home/wso2carbon/wso2-config-volume/wso2/worker/bin/carbon.sh
                subPath: carbon.sh
              - name: mysql-connector-jar
                mountPath: /home/wso2carbon/wso2-artifact-volume/lib                      
        imagePullSecrets:
        - name: ""
        initContainers:          
            - name: init-mysql-db
              image: busybox:1.32
              command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z "wso2am-mysql-db-service" 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL Server has started";']
            - name: init-mysql-connector-download
              image: busybox:1.32
              command:
                - /bin/sh
                - "-c"
                - |
                  set -e
                  connector_version=8.0.17
                  wget https://repo1.maven.org/maven2/mysql/mysql-connector-java/${connector_version}/mysql-connector-java-${connector_version}.jar -P /mysql-connector-jar/
              volumeMounts:
                - name: mysql-connector-jar
                  mountPath: /mysql-connector-jar            
        restartPolicy: Always
        securityContext:
          runAsUser: 802
        serviceAccount: wso2am-svc-account
        serviceAccountName: wso2am-svc-account
        terminationGracePeriodSeconds: 30
        volumes:
          - configMap:
              defaultMode: 420
              name: wso2apim-analytics-worker-conf
            name: wso2apim-analytics-worker-conf
          - configMap:
              defaultMode: 420
              name: wso2apim-analytics-worker-bin
            name: wso2apim-analytics-worker-bin
          - name: mysql-connector-jar
            emptyDir: {}  
  triggers:
      - type: ConfigChange