# DeploymentConfig wso2am-mysql-db-service
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
    name: kcb-wso2am-mysql-db-service
    namespace: kcb-wso2apim
spec:
    replicas: 1
    selector:
      app: kcb-wso2am-mysql-db-service
      release: kcb-wso2am
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: kcb-wso2am-mysql-db-service
          release: kcb-wso2am
      spec:
        containers:
          - env:
              - name: MYSQL_ROOT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    key: mysql-root-password
                    name: kcb-wso2am-mysql-db-service
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    key: mysql-password
                    name: kcb-wso2am-mysql-db-service
              - name: MYSQL_USER
                value: wso2carbon
              - name: MYSQL_DATABASE
            image: 'mysql:5.7.28'
            imagePullPolicy: IfNotPresent
            livenessProbe:
              exec:
                command:
                  - sh
                  - '-c'
                  - 'mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}'
              failureThreshold: 3
              initialDelaySeconds: 120
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 5
            name: wso2am-mysql-db-service
            ports:
              - containerPort: 3306
                name: mysql
                protocol: TCP
            readinessProbe:
              exec:
                command:
                  - sh
                  - '-c'
                  - 'mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}'
              failureThreshold: 3
              initialDelaySeconds: 120
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            resources:
              # requests:
              #   cpu: 500m
              #   memory: 1Gi
            volumeMounts:
              - mountPath: /var/lib/mysql
                name: data
              - mountPath: /etc/mysql/conf.d/mysql.cnf
                name: configurations
                subPath: mysql.cnf
              - mountPath: /docker-entrypoint-initdb.d
                name: migrations
        initContainers:
          - command:
              - rm
              - '-fr'
              - /var/lib/mysql/lost+found
            image: 'busybox:1.29.3'
            imagePullPolicy: IfNotPresent
            name: remove-lost-found
            resources:
              requests:
                cpu: 10m
                memory: 10Mi
            volumeMounts:
              - mountPath: /var/lib/mysql
                name: data
        restartPolicy: Always
        schedulerName: default-scheduler
        volumes:
          - configMap:              
              name: kcb-wso2am-mysql-db-service-configuration
            name: configurations
          - configMap:              
              name: kcb-wso2am-mysql-db-service-initialization
            name: migrations
          - name: data
            persistentVolumeClaim:
              claimName: kcb-wso2am-mysql-db-service
    triggers:
      - type: ConfigChange