# Route wso2am-devportal-route
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: wso2apim-devportal-service
  namespace: wso2apim
spec:
  host: devportal.am.wso2.com
  port:
    targetPort: servlet-https
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: passthrough
  to:
    kind: Service
    name: wso2apim-devportal-service          
