# Service wso2am-gateway-service
apiVersion: v1
kind: Service
metadata:
  name: wso2apim-gateway-service
  namespace: wso2apim
spec:  
  ports:
    - name: pass-through-http
      protocol: TCP
      port: 8284
    - name: pass-through-https
      protocol: TCP
      port: 8247
    - name: servlet-http
      protocol: TCP
      port: 9767
    - name: servlet-https
      protocol: TCP
      port: 9447
  selector:
    deploymentName: wso2apim-gateway
