# Service wso2am-gateway-service
apiVersion: v1
kind: Service
metadata:
  name: wso2am-gateway-service
spec:
  type: ClusterIP
  ports:
    - name: pass-through-https
      port: 8243
      protocol: TCP
      targetPort: 8243
    - name: servlet-https
      port: 9443
      protocol: TCP
      targetPort: 9443
    - name: ws-endpoint
      port: 9099
      protocol: TCP
      targetPort: 9099
  selector:
    deploymentName: wso2am-gw
