# Service wso2am-gateway-service
apiVersion: v1
kind: Service
metadata:
  name: wso2apim-gateway-service
  namespace: wso2apim
spec:  
  ports:
    - name: pass-through-http
      protocol: TCP
      port: 8280
      targetPort: 8280
    - name: pass-through-https
      port: 8243
      protocol: TCP
      targetPort: 8243
    - name: servlet-http
      protocol: TCP
      port: 9763
    - name: servlet-https
      port: 9443
      protocol: TCP
      targetPort: 9443
    - name: ws-endpoint
      port: 9099
      protocol: TCP
      targetPort: 9099
  selector:
    deployment: wso2apim-gw
