apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wso2apim-publisher-local-carbon-database-volume-claim
  namespace : wso2apim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi  

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wso2apim-publisher-solr-indexed-data-volume-claim
  namespace : wso2apim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi  
