apiVersion: v1
kind: ConfigMap
metadata:
  name: wso2apim-tm-conf
  namespace : wso2apim  
data:
  deployment.toml: |-
    [server]
    #hostname = "wso2apim-tm"
    node_ip = "$env{NODE_IP}"
    server_role = "traffic-manager"

    [user_store]
    type = "database_unique_id"

    [super_admin]
    username = "admin"
    password = "admin"
    create_admin_account = true

    [database.apim_db]
    type = "mysql"
    url = "jdbc:mysql://wso2am-mysql-db-service:3306/WSO2AM_DB?useSSL=false&amp;autoReconnect=true&amp;requireSSL=false&amp;verifyServerCertificate=false"
    username = "wso2carbon"
    password = "wso2carbon"
    driver = "com.mysql.cj.jdbc.Driver"

    [database.shared_db]
    type = "mysql"
    url = "jdbc:mysql://wso2am-mysql-db-service:3306/WSO2AM_SHARED_DB?useSSL=false&amp;autoReconnect=true&amp;requireSSL=false&amp;verifyServerCertificate=false"
    username = "wso2carbon"
    password = "wso2carbon"
    driver = "com.mysql.cj.jdbc.Driver"

    [keystore.tls]
    file_name =  "wso2carbon.jks"
    type =  "JKS"
    password =  "wso2carbon"
    alias =  "wso2carbon"
    key_password =  "wso2carbon"

    [truststore]
    file_name = "client-truststore.jks"
    type = "JKS"
    password = "wso2carbon"

    # key manager implementation
    [apim.key_manager]
    service_url = "https://wso2apim-km-service:9443/services/"

    [apim.oauth_config]
    revoke_endpoint = "https://wso2apim-km-service:9443/oauth2/revoke"
    enable_token_encryption = false
    enable_token_hashing = false

    [apim.throttling]
    event_duplicate_url = ["tcp://wso2apim-TM_INDEX-tm-service:5672"]      