apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kcb-wso2apim-tm-shared-executionplans-volume-claim
  namespace : kcb-wso2apim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi  
