# DeploymentConfig wso2am-km-deployment
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: kcb-wso2apim-km-deployment
  namespace: kcb-wso2apim
spec:
  selector:      
      deploymentName: kcb-wso2apim-km-deployment        
  replicas: 1  
  strategy:
      type: Rolling
  template:
      metadata:     
        labels:         
          deploymentName: kcb-wso2apim-km-deployment            
      spec:
        containers:
          - name: kcb-wso2apim-km-deployment
            env:              
              - name: PROFILE_NAME
                value: api-key-manager
              - name: NODE_IP
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: status.podIP
            image: 'wso2/wso2am:3.1.0'
            imagePullPolicy: IfNotPresent
            lifecycle:
              preStop:
                exec:
                  command:
                    - sh
                    - '-c'
                    - '${WSO2_SERVER_HOME}/bin/wso2server.sh stop'            
            livenessProbe:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - nc -z localhost 9443
              failureThreshold: 10
              initialDelaySeconds: 300
              periodSeconds: 60
              successThreshold: 1
              timeoutSeconds: 1
            readinessProbe:
              exec:
                command:
                - /bin/sh
                - -c
                - nc -z localhost 9443
              failureThreshold: 10
              initialDelaySeconds: 300
              periodSeconds: 60
              successThreshold: 1
              timeoutSeconds: 1
            ports:
              - containerPort: 8243
                protocol: TCP
              - containerPort: 9763
                protocol: TCP
              - containerPort: 9443
                protocol: TCP
            # resources:
            #   limits:
            #     cpu: 700m
            #     memory: 2Gi
            #   requests:
            #     cpu: 700m
            #     memory: 2Gi
            volumeMounts:
              - mountPath: /home/wso2carbon/wso2-config-volume/repository/conf/deployment.toml
                name: kcb-wso2apim-km-conf
                subPath: deployment.toml
              # - name: wso2am-entrypoint
              #   mountPath: /home/wso2carbon/docker-entrypoint.sh
              #   subPath: docker-entrypoint.sh           
              - name: kcb-mysql-connector-jar
                mountPath: /home/wso2carbon/wso2-artifact-volume/repository/components/dropins                             
        initContainers:
        - name: init-mysql-db
          image: busybox:1.32
          command: ['sh', '-c', 'echo -e "Checking for the availability of DBMS service"; while ! nc -z "kcb-wso2am-mysql-db-service" 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL Server has started";']
        - name: init-mysql-connector-download
          image: busybox:1.32
          command:
            - /bin/sh
            - "-c"
            - |
              set -e
              connector_version=8.0.17
              wget https://repo1.maven.org/maven2/mysql/mysql-connector-java/${connector_version}/mysql-connector-java-${connector_version}.jar -P /mysql-connector-jar/
          volumeMounts:
            - name: kcb-mysql-connector-jar
              mountPath: /mysql-connector-jar
        serviceAccountName: kcb-wso2am-svc-account
        securityContext:
          privileged: true              
        restartPolicy: Always        
        volumes:
        - configMap:            
            name: kcb-wso2apim-km-conf
          name: kcb-wso2apim-km-conf 
        # - name: wso2am-entrypoint
        #   configMap:
        #     name: wso2am-entrypoint
        #     defaultMode: 0407                     
        - name: kcb-mysql-connector-jar            
          emptyDir: {}           
  triggers:
      - type: ConfigChange


