# Role endpoints-reader-role
apiVersion: authorization.openshift.io/v1
kind: Role
metadata:
  name: kcb-endpoints-reader-role
  namespace: kcb-wso2apim
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list