# RoleBinding endpoints-reader-role-wso2-binding
apiVersion: authorization.openshift.io/v1
groupNames: null
kind: RoleBinding
metadata:
  name: kcb-endpoints-reader-role-wso2-binding
  namespace: kcb-wso2apim
roleRef:
  name: endpoints-reader-role
  namespace: kcb-wso2apim
subjects:
- kind: ServiceAccount
  name: kcb-wso2am-svc-account
  namespace: kcb-wso2apim
userNames:
- system:serviceaccount:kcb-wso2apim:kcb-wso2am-svc-account
