# SecurityContextConstraints wso2am-svc-account-security-context
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: kcb-wso2am-svc-account
  namespace: kcb-wso2apim
allowPrivilegedContainer: true  
allowHostDirVolumePlugin: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
fsGroup:
  type: RunAsAny
users:
- system:kcb-wso2apim:kcb-wso2am-svc-account
volumes:
- '*'