# Route wso2am-mysql-db-route
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kcb-wso2am-mysql-db-service
  namespace: kcb-wso2apim
spec:
  host: db.am.wso2.com
  port:
    targetPort: kcb-mysql
  to:
    kind: Service
    name: kcb-wso2am-mysql-db-service                      
