# ConfigMap wso2am-km-conf
apiVersion: v1
kind: ConfigMap
metadata:
   name: wso2apim-km-conf
   namespace: wso2apim
data:
   deployment.toml: |-
      [server]
      hostname = "wso2apim-km"
      node_ip = "$env{NODE_IP}"
      server_role = "api-key-manager"
      offset = "0"

      [user_store]
      type = "database_unique_id"

      [super_admin]
      username = "admin"
      password = "admin"
      create_admin_account = true

      [database.apim_db]
      type = "mysql"
      url = "jdbc:mysql://wso2am-mysql-db-service:3306/WSO2AM_DB?useSSL=false&amp;autoReconnect=true&amp;requireSSL=false&amp;verifyServerCertificate=false"
      username = "wso2carbon"
      password = "wso2carbon"
      driver = "com.mysql.cj.jdbc.Driver"

      [database.shared_db]
      type = "mysql"
      url = "jdbc:mysql://wso2am-mysql-db-service:3306/WSO2AM_SHARED_DB?useSSL=false&amp;autoReconnect=true&amp;requireSSL=false&amp;verifyServerCertificate=false"
      username = "wso2carbon"
      password = "wso2carbon"
      driver = "com.mysql.cj.jdbc.Driver"

      [keystore.tls]
      file_name =  "wso2carbon.jks"
      type =  "JKS"
      password =  "wso2carbon"
      alias =  "wso2carbon"
      key_password =  "wso2carbon"

      [truststore]
      file_name = "client-truststore.jks"
      type = "JKS"
      password = "wso2carbon"

      [[event_handler]]
      name="userPostSelfRegistration"
      subscriptions=["POST_ADD_USER"]

      [[event_listener]]
      id = "token_revocation"
      type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
      name = "org.wso2.is.notification.ApimOauthEventInterceptor"
      order = 1

      [event_listener.properties]
      notification_endpoint = "https://wso2am-tm-service:${mgt.transport.https.port}/internal/data/v1/notify"
      username = "${admin.username}"
      password = "${admin.password}"
      'header.X-WSO2-KEY-MANAGER' = "default"

      [apim.gateway.environment]
      name = "Production and Sandbox"
      type = "hybrid"
      display_in_api_console = true
      description = "This is a hybrid gateway that handles both production and sandbox token traffic."
      show_as_token_endpoint_url = true
      service_url = "https://wso2am-gateway-service:${mgt.transport.https.port}${carbon.context}services/"
      username= "${admin.username}"
      password= "${admin.password}"

      [transport.https.properties]
      proxyPort = 443

      # Caches
      [apim.cache.km_token]
      enable = false
      expiry_time = 15

      [apim.cache.jwt_claim]
      enable = true
      expiry_time = 900

      # JWT Generation
      [apim.jwt]
      enable = true
      encoding = "base64" # base64,base64url
      #generator_impl = "org.wso2.carbon.apimgt.keymgt.token.JWTGenerator"
      claim_dialect = "http://wso2.org/claims"
      header = "X-JWT-Assertion"
      signing_algorithm = "SHA256withRSA"
      #enable_user_claims = true
      #claims_extractor_impl = "org.wso2.carbon.apimgt.impl.token.DefaultClaimsRetriever"

      [apim.throttling]

      [[apim.throttling.url_group]]
      traffic_manager_urls=["tcp://wso2am-tm-service:9611"]
      traffic_manager_auth_urls=["ssl://wso2am-tm-service:9711"]