# ConfigMap wso2am-km-conf
apiVersion: v1
kind: ConfigMap
metadata:
   name: kcb-wso2apim-km-conf
   namespace: kcb-wso2apim
data:
   deployment.toml: |-
      [server]
      hostname = "wso2apim-km"
      node_ip = "$env{NODE_IP}"
      server_role = "api-key-manager"
      offset = "0"

      [user_store]
      type = "database_unique_id"

      [super_admin]
      username = "admin"
      password = "admin"
      create_admin_account = true

      [database.apim_db]
      type = "mysql"
      url = "jdbc:mysql://kcb-wso2am-mysql-db-service:3306/WSO2AM_DB?useSSL=false&amp;autoReconnect=true&amp;requireSSL=false&amp;verifyServerCertificate=false"
      username = "wso2carbon"
      password = "wso2carbon"
      driver = "com.mysql.cj.jdbc.Driver"

      [database.shared_db]
      type = "mysql"
      url = "jdbc:mysql://kcb-wso2am-mysql-db-service:3306/WSO2AM_SHARED_DB?useSSL=false&amp;autoReconnect=true&amp;requireSSL=false&amp;verifyServerCertificate=false"
      username = "wso2carbon"
      password = "wso2carbon"
      driver = "com.mysql.cj.jdbc.Driver"

      [keystore.tls]
      file_name =  "wso2carbon.jks"
      type =  "JKS"
      password =  "wso2carbon"
      alias =  "wso2carbon"
      key_password =  "wso2carbon"

      [truststore]
      file_name = "client-truststore.jks"
      type = "JKS"
      password = "wso2carbon" 

      [[event_handler]]
      name="userPostSelfRegistration"
      subscriptions=["POST_ADD_USER"]

      [[event_listener]]
      id = "token_revocation"
      type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
      name = "org.wso2.is.notification.ApimOauthEventInterceptor"
      order = 1

      [event_listener.properties]
      notification_endpoint = "https://kcb-wso2am-tm-service:9446/internal/data/v1/notify"
      username= "$ref{super_admin.username}"
      password= "$ref{super_admin.password}"
      'header.X-WSO2-KEY-MANAGER' = "default"      
      
      # Traffic Manager configurations
      [apim.throttling]
      username= "$ref{super_admin.username}"
      password= "$ref{super_admin.password}"
      throttle_decision_endpoints = ["tcp://kcb-wso2am-tm-service:5675"]

      [[apim.throttling.url_group]]
      traffic_manager_urls = ["tcp://kcb-wso2am-tm-service:9614"]
      traffic_manager_auth_urls = ["ssl://kcb-wso2am-tm-service:9714"]