# PersistentVolumeClaim wso2am-volume-claim-synapse-configs-volumen-claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kcb-wso2apim-volume-claim-synapse-configs
  namespace: kcb-wso2apim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi